### ISSUE TITLE
👋 hello!

### ISSUE THREAD

**Issue by peterldowns** [thomasskk/pg-migrate#1]
Hey, I found this project because I saw you just started following me. Looks like you may be using [pgmigrate](https://github.com/peterldowns/pgmigrate) as inspiration? Go for it! If you're writing this because pgmigrate is missing any features, or has bugs or something, please let me know and I'll do my best to fix them. 

🫡 cheers!

**Comment by thomasskk** [comment]
@peterldowns  Hey, yes I used it as an inspiration and wanted to learn more about sql migrations. I found your way or managing migrations very interesting. Im writing it in js to use it as a node package in my project and I wanted something that I could maintain and change as needed.
cheers ! 🫡

**Comment by peterldowns** [comment]
Sounds like fun — if you have any questions on why I did something a certain way, or discover a bug, please reach out. Totally makes sense to reimplement it in ts/js if you're primarily using that language, although I do want to point out that you should be able to use the pgmigrate CLI and/or container to run migrations for any project, in development and production, regardless of language.

Fun fact, I got started with pgmigrate for similar reasons: I was using [golang-migrate/migrate](https://github.com/golang-migrate/migrate) but wanted some improvements, so I started to use [adlio/schema](https://github.com/adlio/schema) but realized it would be easier to just write it myself. 

Enjoy!
